services:
  backend:
    build: .
    container_name: ssd_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: ssd_nginx
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    depends_on:
      backend:
        condition: service_healthy
