name: CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ssd-diagnostic-suite/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y smartmontools nvme-cli

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt ruff

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Run tests
        run: |
          pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend image
        run: |
          docker build -t ssd-backend:ci ssd-diagnostic-suite/backend
